routes/admin.php
<?php

use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

Route::get('/', 'Dashboard@index')->name('admin_dashboard');

Route::get('/events', function () {
    return 'EVENTOS';
})->name('admin_events');

Route:: catch(function () {
    throw new NotFoundHttpException();
});

Route::get('search-user', function (Request $request) {
    $pattern = '/[A-Za-z][A-Za-z ]+/';
    $query = $request->get('query');
    if (preg_match($pattern, $query)) {
        return response(App\User::where('name', 'like', "%$query%")->select('name', 'id')->get());
    } else {
        return response()->json([]);
    }
})->name('search-user');

Route::resource('/slides', 'SlideController', ['except' => 'show']);
Route::resource('/menus', 'MenuController', ['except' => 'show']);
Route::resource('/roles', 'RolesController');
Route::resource('/abilities', 'AbilitiesController', ['except' => 'show']);

Route::put('/roles-menu/{role}', 'RolesController@menu')->name('roles.menu')->middleware('can:role-menu');
Route::put('/roles-abilities/{role}', 'RolesController@abilities')->name('roles.ability')->middleware('can:role-ability');

Route::resource('/user', 'UserController');
Route::any('/user-change-password/{user}', 'UserController@changePassword')->name('change-password-user')->middleware('can:password-user');
Route::any('/user-change-role/{user}', 'UserController@changeRole')->name('change-role-user')->middleware('can:role-user');

Route::resource('/admin', 'AdminController');
Route::any('/admin-change-password/{admin}', 'AdminController@changePassword')->name('change-password-admin')->middleware('can:password-admin');
Route::any('/admin-change-role/{admin}', 'AdminController@changeRole')->name('change-role-admin')->middleware('can:role-admin');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/master/{router?}', 'HomeController@getRouter')->name('master')->middleware('auth:web,admin');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth:web,admin');
Route::get('/cambiar-clave', 'HomeController@showChangePasswordForm')->name('changePassword')->middleware('auth:web,admin');
Route::post('/cambiar-clave', 'HomeController@changePassword')->name('changePassword')->middleware('auth:web,admin');
Route::get('/cambiar-foto', 'HomeController@showChangePictureForm')->name('changePicture')->middleware('auth:web,admin');
Route::post('/cambiar-foto', 'HomeController@changePicture')->name('changePicture')->middleware('auth:web,admin');



// Admin Login
Route::get('core-admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('core-admin/login', 'Admin\LoginController@login');
Route::post('core-admin/logout', 'Admin\LoginController@logout')->name('admin.logout');

require __DIR__ . '/modules/notifications.php';
require __DIR__ . '/modules/guest.php';

Route::view('/readme', 'readme')->name('readme')->middleware('auth:web,admin');

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use Bouncer;
use Illuminate\Http\Request;
use Silber\Bouncer\Database\Role;
use App\Core\Eloquent\Security\Menu;
use App\Http\Controllers\Controller;
use Silber\Bouncer\Database\Ability;
use App\Core\Repositories\SecurityRPY;
use App\Core\Eloquent\Security\RoleMenu;
use App\Http\Requests\Admin\RoleRequest;

class RolesController extends Controller
{
    private $objSecurityRPY;

    public function __construct(SecurityRPY $objSecurityRPY)
    {
        $this->abilityCRUD('role', true);
        $this->objSecurityRPY = $objSecurityRPY;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.roles.index')->with([
            'filter' => $request->filter,
            'roles' => Bouncer::role()->where('name', 'like', "%{$request->filter}%")->get()->paginateCollection(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param App\Http\Requests\Admin\RoleRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        Role::create($request->validated());
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('roles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('admin.roles.edit')->with(['role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(RoleRequest $request, $id)
    {
        Role::where('id', $id)
            ->update($request->validated());
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Role $role
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('roles.index');
    }

    /**
     * Show Roles with menus.
     *
     * @param Role $role
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //(auth()->user()->assign('administrador'));

        return view('admin.roles.role-menu-ability', compact('role'))->with([
            'abilities' => Bouncer::ability()->get(),
            'menus' => Menu::menus([$role->id]),
            'abilityRol' => $this->objSecurityRPY->permissionByRol($role->id)->pluck('ability_id')->toArray(),
        ]);
    }

    public function menu(Request $request, Role $role)
    {
        $this->validate($request, ['menu.*' => 'required|exists:menus,id', 'menu' => 'required']);
        DB::transaction(function () use (&$role, &$request) {
            RoleMenu::where('role_id', '=', $role->id)->delete();
            $data = [];
            foreach ($request->menu as $menu) {
                $data[] = ['menu_id' => $menu, 'role_id' => $role->id, 'created_at' => getDateSQL(), 'updated_at' => getDateSQL()];
            }
            RoleMenu::insert($data);
        });

        session()->flash('status', __('Proccess OK'));

        return redirect()->route('roles.index');
    }

    public function abilities(Request $request, Role $role)
    {
        $this->validate($request, [
            'ability.*' => 'required|exists:bouncer_abilities,id',
        ]);
        DB::transaction(function () use (&$role, &$request) {
            $this->objSecurityRPY->permissionByRol($role->id)->delete();
            Bouncer::allow($role)->to($request->ability);
        });

        session()->flash('status', __('Proccess OK'));

        return redirect()->route('roles.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')
@section('titleOption',__('options.roles'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4>@lang('options.form',['action'=>__('options.add-edit'),'name'=>__('options.roles')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>'roles.store','files'=>true]) !!}
                                    <div class="form-body">
                                         <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('labels.admin',['name'=>__('options.roles')])</legend>
                                        <div class="row p-t-20">
                                            <div class="col-md-6">
                                                {!! Field::text('name',['required'=>true,'label'=>__('labels.name'),'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::text('title',['required'=>true,'label'=>__('labels.description'),'placeholder'=>__('labels.input',['name'=>__('labels.description')])])!!}
                                            </div>      
                                        </div>
                                    </div>
                                
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                        <a href="{{route('roles.index')}}" class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
             </div>     
    </div>
</div>
@endsection

@section('jsCustom')
<script type="text/javascript" src="/plugins/waves.js"></script>
<script type="text/javascript" src="{{assets('/plugins/waves.js')}}"></script>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')
@section('titleOption',__('options.roles'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4>@lang('options.form',['action'=>__('options.add-edit'),'name'=>__('options.roles')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>['roles.update',$role],'method'=>'PUT']) !!}
                                    <div class="form-body">
                                         <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('labels.admin',['name'=>__('options.roles')])</legend>
                                        <div class="row p-t-20">
                                            <div class="col-md-6">
                                                {!! Field::text('name',$role->name,['required'=>true,'label'=>__('labels.name'),'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::text('title',$role->title,['required'=>true,'label'=>__('labels.description'),'placeholder'=>__('labels.input',['name'=>__('labels.description')])])!!}
                                            </div>      
                                        </div>
                                    </div>
                                
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                        <a href="{{route('roles.index')}}"  class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
             </div>     
    </div>
</div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.app')
@section('titleOption',__('options.roles'))
@section('bar-search')
    @include('partials.search',[
      'route'=>route('roles.index'),
      'placeholder'=>__('labels.search',['name'=>__('labels.title')]),
      'filter'=>$filter
    ])
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                       

                    <div class="card-header header-elements-inline">
                        <h5 class="card-title">@lang('options.table',['name'=>__('options.roles')])</h5>
                        <div class="header-elements">
                            <div class="list-icons">
                            @can ('create-role')
                                        <a href="{{route('roles.create')}}" class="list-icons-item btn btn-primary btn-rounded waves-effect waves-light btn-sm text-white">
                                            @lang('labels.add')</a>
                              @endcan    
                            </div>
                        </div>
                    </div>


                     


                    <div class="card-body collapse show">
                        
                        
                        <table class="table product-overview table-responsive-stack">
                            <thead>
                                <tr>
                                    <th class="text-center">@lang('labels.name')</th>
                                    <th class="text-center"> @lang('labels.description') </th>
                                    <th class="text-center"> @lang('labels.actions')  </th>
                                </tr>
                            </thead>
                            <tbody>
                               @forelse($roles as $role)
                                <tr>
                                    <td class="text-center">{{$role->name}}</td>
                                    <td class="text-center">{{$role->title}}</td>
                                    <td class="text-center"> 
                                        <form  action="{{route('roles.destroy',$role->id)}}" method="POST" class="form-horizontal" @submit.prevent="deleteAlert($event)">
                                            @method('DELETE')
                                            @csrf
                                            @can('show-role')
                                                <a href="{{route('roles.show',$role->id)}}"><span class="btn badge badge-success waves-effect waves-light  text-uppercase">@lang('options.menu-ability')</span></a>
                                            @endcan
                                            @can('update-role')
                                                <a href="{{route('roles.edit',$role->id)}}"><span class="btn badge  waves-effect waves-light badge-info">@lang('labels.edit')</span></a>
                                            @endcan
                                            @can ('delete-role')
                                                <button type="submit" class="btn badge waves-effect waves-light  badge-danger"><span>@lang('labels.delete')</span></button> 
                                            @endcan
                                        </form>

                                    </td>
                                </tr>
                               @empty
                               <tr><td colspan="6">@lang('labels.notresults')</td></tr>
                               @endforelse
                            </tbody>
                        </table>
                        <div class="text-right">
                            {!! $roles->appends(['filter' => $filter])->render()!!}
                    </div>
                    </div>
                </div>

             </div>     
    </div>
</div>
@endsection

resources/views/admin/roles/role-menu-ability.blade.php
@extends('layouts.app')
@section('titleOption',__('options.menu-ability'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-lg-6">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4>@lang('labels.admin',['name'=>__('options.menus')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>['roles.menu',$role],'method'=>'PUT']) !!}
                                        <div class="form-body">
                                                 <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('options.roles'): {{$role->title}}</legend>
                                                <div class="row p-t-20">
                                                    <div class="col-md-12">
                                                            @include('partials.menu-tree',['menus'=>$menus])
                                                    </div>    
                                                </div>
                                            </div>                                            
                                        <br/>
                                        <div class="form-actions">
                                            @can ('role-menu')
                                                <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                            @endcan
                                        <a href="{{route('roles.index')}}" class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                              
                               
                            </div>
                        </div>
             </div>     
             <div class="col-lg-10">
                    <div class="card card-outline-info">
                        <div class="card-header">
                            <h4 class="m-b-0 text-white">@lang('labels.admin',['name'=>__('options.abilities')])</h4>
                        </div>
                        <div class="card-body">
                            {!! Form::open(['route'=>['roles.ability',$role],'method'=>'PUT']) !!}
                                    <div class="form-body">
                                            <div class="row">
                                                @foreach($abilities as $keyAbility => $ability)
                                                    <p class="col-lg-3" style="margin: 0px" >
                                                                    <label class="pointerSkill">
                                                                        <input id="ability-{{ $keyAbility }}" type="checkbox" @if(in_array($ability->id,$abilityRol)) checked @endif                                                                    
                                                                        name="ability[]" value="{{ $ability->id}}">
                                                                        <label for="ability-{{ $keyAbility }}" class="check-box"></label>&nbsp; <span class="text-small"  data-popup="tooltip"  title="" data-original-title="{{$ability->title}}"> {{$ability->name}}</span>
                                                                    </label>
                                                                  
                                                            </p>
                                                @endforeach
                                            </div>
                                        </div>   
                                    <div class="form-actions">
                                    @can ('role-ability')
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                    @endcan
                                    <a href="{{route('roles.index')}}" class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                </div>
                            {!! Form::close() !!}
                          
                           
                        </div>
                    </div>
         </div>     
    </div>
</div>
@endsection