routes/admin.php
<?php

use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

Route::get('/', 'Dashboard@index')->name('admin_dashboard');

Route::get('/events', function () {
    return 'EVENTOS';
})->name('admin_events');

Route:: catch(function () {
    throw new NotFoundHttpException();
});

Route::get('search-user', function (Request $request) {
    $pattern = '/[A-Za-z][A-Za-z ]+/';
    $query = $request->get('query');
    if (preg_match($pattern, $query)) {
        return response(App\User::where('name', 'like', "%$query%")->select('name', 'id')->get());
    } else {
        return response()->json([]);
    }
})->name('search-user');

Route::resource('/slides', 'SlideController', ['except' => 'show']);
Route::resource('/menus', 'MenuController', ['except' => 'show']);
Route::resource('/roles', 'RolesController');
Route::resource('/abilities', 'AbilitiesController', ['except' => 'show']);

Route::put('/roles-menu/{role}', 'RolesController@menu')->name('roles.menu')->middleware('can:role-menu');
Route::put('/roles-abilities/{role}', 'RolesController@abilities')->name('roles.ability')->middleware('can:role-ability');

Route::resource('/user', 'UserController');
Route::any('/user-change-password/{user}', 'UserController@changePassword')->name('change-password-user')->middleware('can:password-user');
Route::any('/user-change-role/{user}', 'UserController@changeRole')->name('change-role-user')->middleware('can:role-user');

Route::resource('/admin', 'AdminController');
Route::any('/admin-change-password/{admin}', 'AdminController@changePassword')->name('change-password-admin')->middleware('can:password-admin');
Route::any('/admin-change-role/{admin}', 'AdminController@changeRole')->name('change-role-admin')->middleware('can:role-admin');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/master/{router?}', 'HomeController@getRouter')->name('master')->middleware('auth:web,admin');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth:web,admin');
Route::get('/cambiar-clave', 'HomeController@showChangePasswordForm')->name('changePassword')->middleware('auth:web,admin');
Route::post('/cambiar-clave', 'HomeController@changePassword')->name('changePassword')->middleware('auth:web,admin');
Route::get('/cambiar-foto', 'HomeController@showChangePictureForm')->name('changePicture')->middleware('auth:web,admin');
Route::post('/cambiar-foto', 'HomeController@changePicture')->name('changePicture')->middleware('auth:web,admin');



// Admin Login
Route::get('core-admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('core-admin/login', 'Admin\LoginController@login');
Route::post('core-admin/logout', 'Admin\LoginController@logout')->name('admin.logout');

require __DIR__ . '/modules/notifications.php';
require __DIR__ . '/modules/guest.php';

Route::view('/readme', 'readme')->name('readme')->middleware('auth:web,admin');

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Core\Eloquent\Security\Menu;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\MenuRequest;
use Facades\App\Core\Contracts\TableRepository;

class MenuController extends Controller
{
    public function __construct()
    {
        $this->abilityCRUD('menu');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.menu.index')->with(['filter' => $request->filter,
        'menus' => TableRepository::forMenus($request->filter), ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.menu.create')->with(['menus' => Menu::pluck('name', 'id')->toArray()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(MenuRequest $request)
    {
        Menu::create($request->validated());
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('menus.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Core\Eloquent\Security\Menu $menu
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        return view('admin.menu.edit')->with(['menu' => $menu, 'menus' => Menu::pluck('name', 'id')->toArray()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request         $request
     * @param \App\Core\Eloquent\Security\Menu $menu
     *
     * @return \Illuminate\Http\Response
     */
    public function update(MenuRequest $request, Menu $menu)
    {
        $menu->fill($request->validated());
        $menu->save();
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('menus.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Core\Eloquent\Security\Menu $menu
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        $menu->delete();
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('menus.index');
    }
}

resources/views/admin/menu/create.blade.php
@extends('layouts.app')
@section('titleOption',__('options.menus'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4 >@lang('options.form',['action'=>__('options.add-edit'),'name'=>__('options.menus')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>'menus.store','files'=>true]) !!}
                                    <div class="form-body">
                                         <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('labels.admin',['name'=>__('options.menus')])</legend>
                                        <div class="row p-t-20">
                                            <div class="col-md-6">
                                                {!! Field::text('name',['required'=>true,'label'=>__('labels.name'),'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::text('route',['label'=>__('labels.route'),'placeholder'=>__('labels.input',['name'=>__('labels.route')])])!!}
                                            </div>
                                            <div class="col-md-6">
                                                {!! Field::text('icon',['label'=>__('labels.icon'),'placeholder'=>__('labels.input',['name'=>__('labels.icon')])])!!}
                                            </div> 
                                           
                                            <div class="col-md-6">
                                                {!! Field::number('order',['required'=>true,'label'=>__('labels.order'),'placeholder'=>__('labels.input',['name'=>__('labels.order')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::select('parent',$menus,null,['label'=>__('labels.parent'),'empty'=>__('labels.select',['name'=>__('labels.parent')])])!!}
                                            </div>
                                                
                                        </div>
                                    </div>
                                
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                        <a href="{{route('menus.index')}}" class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
             </div>     
    </div>
</div>
@endsection

resources/views/admin/menu/edit.blade.php
@extends('layouts.app')
@section('titleOption',__('options.menus'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4 >@lang('options.form',['action'=>__('options.add-edit'),'name'=>__('options.menus')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>['menus.update',$menu],'method'=>'PUT']) !!}
                                    <div class="form-body">
                                        <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('labels.admin',['name'=>__('options.menus')])</legend>
                                        <div class="row p-t-20">
                                            <div class="col-md-6">
                                                {!! Field::text('name',$menu->name,['required'=>true,'label'=>__('labels.name'),'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::text('route',$menu->route,['label'=>__('labels.route'),'placeholder'=>__('labels.input',['name'=>__('labels.route')])])!!}
                                            </div>
                                            <div class="col-md-6">
                                                {!! Field::text('icon',$menu->icon,['label'=>__('labels.icon'),'placeholder'=>__('labels.input',['name'=>__('labels.icon')])])!!}
                                            </div> 
                                           
                                            <div class="col-md-6">
                                                {!! Field::number('order',$menu->order,['required'=>true,'label'=>__('labels.order'),'placeholder'=>__('labels.input',['name'=>__('labels.order')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::select('parent',$menus,$menu->parent,['label'=>__('labels.parent'),'empty'=>__('labels.select',['name'=>__('labels.parent')])])!!}
                                            </div>
                                                
                                        </div>
                                    </div>
                                
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                        <a href="{{route('menus.index')}}"  class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
             </div>     
    </div>
</div>
@endsection

resources/views/admin/menu/index.blade.php
@extends('layouts.app')
@section('titleOption',__('options.menus'))
@section('bar-search')
    @include('partials.search',[
      'route'=>route('menus.index'),
      'placeholder'=>__('labels.search',['name'=>__('labels.name')]),
      'filter'=>$filter
    ])
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    

                    <div class="card-header header-elements-inline">
                        <h5 class="card-title">@lang('options.table',['name'=>__('options.menus')])</h5>
                        <div class="header-elements">
                            <div class="list-icons">
                           @can ('create-menu')
                                        <a href="{{route('menus.create')}}" class="list-icons-item btn btn-primary btn-rounded waves-effect waves-light btn-sm text-white">
                                            @lang('labels.add')</a>
                                    @endcan
                            </div>
                        </div>
                    </div>




                    <div class="card-body collapse show">
                        <table class="table product-overview table-responsive-stack">
                            <thead>
                                <tr>
                                    <th class="text-center">@lang('labels.name')</th>
                                    <th class="text-center"> @lang('labels.parent') </th>
                                    <th  class="text-center"> @lang('labels.order') </th>
                                    <th class="text-center"> @lang('labels.route') </th>
                                    <th class="text-center"> @lang('labels.icon') </th>
                                    <th class="text-center"> @lang('labels.actions')  </th>
                                </tr>
                            </thead>
                            <tbody>
                               @forelse($menus as $menu)
                                <tr>
                                    <td class="text-center">{{$menu->name}}</td>
                                    <td class="text-center">{{$menu->father}}</td>
                                    <td class="text-center">{{$menu->order}}</td>
                                    <td class="text-center">{{$menu->route}}</td>
                                    <td class="text-center"><i class="{{ $menu->icon}}"></i></td>
                                    <td class="text-center"> 
                                        <form  action="{{route('menus.destroy',$menu->id)}}" method="POST" class="form-horizontal" @submit.prevent="deleteAlert($event)">
                                            @method('DELETE')
                                            @csrf
                                            @can ('update-menu')
                                                <a href="{{route('menus.edit',$menu->id)}}"><span class="btn badge waves-effect waves-light badge-info">@lang('labels.edit')</span></a>
                                            @endcan
                                            @can ('delete-menu')
                                                <button type="submit" class="btn badge waves-effect waves-light badge-danger"><span>@lang('labels.delete')</span></button> 
                                            @endcan
                                        </form>
                                    </td>
                                </tr>
                               @empty
                               <tr><td colspan="6">@lang('labels.notresults')</td></tr>
                               @endforelse
                            </tbody>
                        </table>
                        <div class="text-right">
                            {!! $menus->appends(['filter' => $filter])->render()!!}
                    </div>
                    </div>
                </div>

             </div>     
    </div>
</div>
@endsection