routes/admin.php
<?php

use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

Route::get('/', 'Dashboard@index')->name('admin_dashboard');

Route::get('/events', function () {
    return 'EVENTOS';
})->name('admin_events');

Route:: catch(function () {
    throw new NotFoundHttpException();
});

Route::get('search-user', function (Request $request) {
    $pattern = '/[A-Za-z][A-Za-z ]+/';
    $query = $request->get('query');
    if (preg_match($pattern, $query)) {
        return response(App\User::where('name', 'like', "%$query%")->select('name', 'id')->get());
    } else {
        return response()->json([]);
    }
})->name('search-user');

Route::resource('/slides', 'SlideController', ['except' => 'show']);
Route::resource('/menus', 'MenuController', ['except' => 'show']);
Route::resource('/roles', 'RolesController');
Route::resource('/abilities', 'AbilitiesController', ['except' => 'show']);

Route::put('/roles-menu/{role}', 'RolesController@menu')->name('roles.menu')->middleware('can:role-menu');
Route::put('/roles-abilities/{role}', 'RolesController@abilities')->name('roles.ability')->middleware('can:role-ability');

Route::resource('/user', 'UserController');
Route::any('/user-change-password/{user}', 'UserController@changePassword')->name('change-password-user')->middleware('can:password-user');
Route::any('/user-change-role/{user}', 'UserController@changeRole')->name('change-role-user')->middleware('can:role-user');

Route::resource('/admin', 'AdminController');
Route::any('/admin-change-password/{admin}', 'AdminController@changePassword')->name('change-password-admin')->middleware('can:password-admin');
Route::any('/admin-change-role/{admin}', 'AdminController@changeRole')->name('change-role-admin')->middleware('can:role-admin');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/master/{router?}', 'HomeController@getRouter')->name('master')->middleware('auth:web,admin');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth:web,admin');
Route::get('/cambiar-clave', 'HomeController@showChangePasswordForm')->name('changePassword')->middleware('auth:web,admin');
Route::post('/cambiar-clave', 'HomeController@changePassword')->name('changePassword')->middleware('auth:web,admin');
Route::get('/cambiar-foto', 'HomeController@showChangePictureForm')->name('changePicture')->middleware('auth:web,admin');
Route::post('/cambiar-foto', 'HomeController@changePicture')->name('changePicture')->middleware('auth:web,admin');



// Admin Login
Route::get('core-admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('core-admin/login', 'Admin\LoginController@login');
Route::post('core-admin/logout', 'Admin\LoginController@logout')->name('admin.logout');

require __DIR__ . '/modules/notifications.php';
require __DIR__ . '/modules/guest.php';

Route::view('/readme', 'readme')->name('readme')->middleware('auth:web,admin');

app/Http/Controllers/Admin/AbilitiesController.php
<?php

namespace App\Http\Controllers\Admin;

use Bouncer;
use Illuminate\Http\Request;
use Silber\Bouncer\Database\Ability;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AbilityRequest;

class AbilitiesController extends Controller
{
    public function __construct()
    {
        $this->abilityCRUD('ability');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.abilities.index')->with(['filter' => $request->filter,
        'abilities' => Bouncer::ability()->where('name', 'like', "%{$request->filter}%")->get()->paginateCollection(), ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.abilities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param App\Http\Requests\Admin\AbilityRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(AbilityRequest $request)
    {
        Ability::create($request->validated());
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('abilities.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Ability $ability)
    {
        return view('admin.abilities.edit')->with(['ability' => $ability]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(AbilityRequest $request, $id)
    {
        Ability::where('id', $id)
        ->update($request->validated());
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('abilities.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Ability $ability
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ability $ability)
    {
        $ability->delete();
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('abilities.index');
    }
}

resources/views/admin/abilities/create.blade.php
@extends('layouts.app')
@section('titleOption',__('options.abilities'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4>@lang('options.form',['action'=>__('options.add-edit'),'name'=>__('options.abilities')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>'abilities.store','files'=>true]) !!}
                                    <div class="form-body">
                                        <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('labels.admin',['name'=>__('options.abilities')])</legend>
                                        <div class="row p-t-20">
                                            <div class="col-md-6">
                                                {!! Field::text('name',['required'=>true,'label'=>__('labels.name'),'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::text('title',['required'=>true,'label'=>__('labels.description'),'placeholder'=>__('labels.input',['name'=>__('labels.description')])])!!}
                                            </div>      
                                        </div>
                                    </div>
                                
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                        <a href="{{route('abilities.index')}}" class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
             </div>     
    </div>
</div>
@endsection

resources/views/admin/abilities/edit.blade.php
@extends('layouts.app')
@section('titleOption',__('options.abilities'))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                        <div class="card card-outline-info">
                            <div class="card-header">
                                <h4>@lang('options.form',['action'=>__('options.add-edit'),'name'=>__('options.abilities')])</h4>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route'=>['abilities.update',$ability],'method'=>'PUT']) !!}
                                    <div class="form-body">
                                        <legend class="font-weight-semibold text-uppercase font-size-sm">@lang('labels.admin',['name'=>__('options.abilities')])</legend>
                                        <div class="row p-t-20">
                                            <div class="col-md-6">
                                                {!! Field::text('name',$ability->name,['required'=>true,'label'=>__('labels.name'),'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                            </div> 
                                            <div class="col-md-6">
                                                {!! Field::text('title',$ability->title,['required'=>true,'label'=>__('labels.description'),'placeholder'=>__('labels.input',['name'=>__('labels.description')])])!!}
                                            </div>      
                                        </div>
                                    </div>
                                
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info waves-effect waves-light"> <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                        <a href="{{route('abilities.index')}}" class="btn btn-danger waves-effect waves-light text-white"><i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
             </div>     
    </div>
</div>
@endsection

resources/views/admin/abilities/index.blade.php
@extends('layouts.app')
@section('titleOption',__('options.abilities'))
@section('bar-search')
    @include('partials.search',[
      'route'=>route('abilities.index'),
      'placeholder'=>__('labels.search',['name'=>__('options.abilities')]),
      'filter'=>$filter
    ])
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                       


                    <div class="card-header header-elements-inline">
                        <h5 class="card-title">@lang('options.table',['name'=>__('options.abilities')])</h5>
                        <div class="header-elements">
                            <div class="list-icons">
                           @can ('create-ability')
                                        <a href="{{route('abilities.create')}}" class="list-icons-item btn btn-primary btn-rounded waves-effect waves-light btn-sm text-white">
                                            @lang('labels.add')</a>
                                    @endcan
                            </div>
                        </div>
                    </div>


                    <div class="card-body  collapse show">
                        <table class="table product-overview table-responsive-stack">
                            <thead>
                                <tr>
                                    <th class="text-center">@lang('labels.name')</th>
                                    <th class="text-center"> @lang('labels.description') </th>
                                    <th class="text-center"> @lang('labels.actions')  </th>
                                </tr>
                            </thead>
                            <tbody>
                               @forelse($abilities as $ability)
                                <tr>
                                    <td class="text-center">{{$ability->name}}</td>
                                    <td class="text-center">{{$ability->title}}</td>
                                    <td class="text-center"> 
                                        <form  action="{{route('abilities.destroy',$ability->id)}}" method="POST" class="form-horizontal" @submit.prevent="deleteAlert($event)">
                                            @method('DELETE')
                                            @csrf
                                            @can ('update-ability')
                                                <a href="{{route('abilities.edit',$ability->id)}}"><span class="btn waves-effect waves-light badge badge-info">@lang('labels.edit')</span></a>
                                            @endcan
                                            @can('delete-ability')
                                                <button type="submit" class="btn waves-effect waves-light badge badge-danger"><span>@lang('labels.delete')</span></button> 
                                            @endcan
                                        </form>
                                    </td>
                                </tr>
                               @empty
                               <tr><td colspan="6">@lang('labels.notresults')</td></tr>
                               @endforelse
                            </tbody>
                        </table>
                        <div class="text-right">
                            {!! $abilities->appends(['filter' => $filter])->render()!!}
                    </div>
                    </div>
                </div>

             </div>     
    </div>
</div>
@endsection