routes/admin.php
<?php

use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

Route::get('/', 'Dashboard@index')->name('admin_dashboard');

Route::get('/events', function () {
    return 'EVENTOS';
})->name('admin_events');

Route:: catch(function () {
    throw new NotFoundHttpException();
});

Route::get('search-user', function (Request $request) {
    $pattern = '/[A-Za-z][A-Za-z ]+/';
    $query = $request->get('query');
    if (preg_match($pattern, $query)) {
        return response(App\User::where('name', 'like', "%$query%")->select('name', 'id')->get());
    } else {
        return response()->json([]);
    }
})->name('search-user');

Route::resource('/slides', 'SlideController', ['except' => 'show']);
Route::resource('/menus', 'MenuController', ['except' => 'show']);
Route::resource('/roles', 'RolesController');
Route::resource('/abilities', 'AbilitiesController', ['except' => 'show']);

Route::put('/roles-menu/{role}', 'RolesController@menu')->name('roles.menu')->middleware('can:role-menu');
Route::put('/roles-abilities/{role}', 'RolesController@abilities')->name('roles.ability')->middleware('can:role-ability');

Route::resource('/user', 'UserController');
Route::any('/user-change-password/{user}', 'UserController@changePassword')->name('change-password-user')->middleware('can:password-user');
Route::any('/user-change-role/{user}', 'UserController@changeRole')->name('change-role-user')->middleware('can:role-user');

Route::resource('/admin', 'AdminController');
Route::any('/admin-change-password/{admin}', 'AdminController@changePassword')->name('change-password-admin')->middleware('can:password-admin');
Route::any('/admin-change-role/{admin}', 'AdminController@changeRole')->name('change-role-admin')->middleware('can:role-admin');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

Route::get('/master/{router?}', 'HomeController@getRouter')->name('master')->middleware('auth:web,admin');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth:web,admin');
Route::get('/cambiar-clave', 'HomeController@showChangePasswordForm')->name('changePassword')->middleware('auth:web,admin');
Route::post('/cambiar-clave', 'HomeController@changePassword')->name('changePassword')->middleware('auth:web,admin');
Route::get('/cambiar-foto', 'HomeController@showChangePictureForm')->name('changePicture')->middleware('auth:web,admin');
Route::post('/cambiar-foto', 'HomeController@changePicture')->name('changePicture')->middleware('auth:web,admin');



// Admin Login
Route::get('core-admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('core-admin/login', 'Admin\LoginController@login');
Route::post('core-admin/logout', 'Admin\LoginController@logout')->name('admin.logout');

require __DIR__ . '/modules/notifications.php';
require __DIR__ . '/modules/guest.php';

Route::view('/readme', 'readme')->name('readme')->middleware('auth:web,admin');

app/User.php
<?php

namespace App;

use App\Core\Traits\DateTrait;
use App\Notifications\CustomResetPassword;
use App\Core\Eloquent\DatabaseNotification;
use App\Core\Traits\HasDatabaseNotifications;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\RoutesNotifications;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Hash;

class User extends Authenticatable
{
    use HasRolesAndAbilities, SoftDeletes,
    DateTrait,HasDatabaseNotifications, RoutesNotifications;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status', 'created_by',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'admin' => 'boolean',
    ];

    public function isAdmin()
    {
        return false;
    }

    /**
     * Funcion para resetear clave de usuario.
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new CustomResetPassword($token));
    }

    public function notifications()
    {
        return $this->morphMany(DatabaseNotification::class, 'notifiable')->orderBy('created_at', 'desc');
    }

    public function scopeName($query, $name)
    {
        return $query->where('name', 'like', "%$name%");
    }

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    public static function boot()
    {
        static::creating(function ($model) {
            $model->created_by = currentUser()->id;
        });

        static::deleting(function ($model) {
        });

        parent::boot();
    }

    public function createdUser()
    {
        return $this->belongsTo(Admin::class, 'created_by');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Silber\Bouncer\Database\Role;
use App\Http\Controllers\Controller;
use App\Core\Repositories\SecurityRPY;
use App\Http\Requests\Admin\UserRequest;
use Facades\App\Core\Contracts\TableRepository;
use DB;
use Hash;
class UserController extends Controller
{
    private $objSecurityRPY;

    public function __construct(SecurityRPY $objSecurityRPY)
    {
        $this->abilityCRUD('user', true);
        $this->objSecurityRPY = $objSecurityRPY;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return view('admin.users.users')->with(['filter' => $request->filter,
        'users' => TableRepository::forUsers($request->filter), ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create')->with([
            'roles' => $this->objSecurityRPY->roles(), 'type' => 'user', ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        DB::transaction(function () use (&$request) {
            $this->objSecurityRPY->createUserOrAdminAndRole(new User(), $request->validated(), $request->role, true);
        });

        session()->flash('status', __('Proccess OK'));

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\User $user
     *
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show')->with(['type' => 'user', 'user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\User $user
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit')->with([
            'roles' => $this->objSecurityRPY->roles(), 'user' => $user, 'type' => 'user', ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\User                $user
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        DB::transaction(function () use (&$request,&$user) {
            $this->objSecurityRPY->createUserOrAdminAndRole($user, $request->validated(), $request->role, false);
        });

        session()->flash('status', __('Proccess OK'));

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\User $user
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->status = $user->status == 'A' ? 'I' : 'A';
        $user->save();
        session()->flash('status', __('Proccess OK'));

        return redirect()->route('user.index');
    }

    public function changePassword(Request $request, User $user)
    {
        if ($request->method() == 'GET') {
            return view('admin.users.password', compact('user'))->with(['password' => str_random(6), 'type' => 'user']);
        } else {
            $this->validate($request, ['password' => 'required|min:6']);
            $user->password =$request->password;
            $user->save();
            session()->flash('status', __('Proccess OK'));

            return redirect()->route('user.index');
        }
    }

    public function changeRole(Request $request, User $user)
    {
        if ($request->method() == 'GET') {
            return view('admin.users.role', compact('user'))->with(['roles' => $this->objSecurityRPY->roles(), 'type' => 'user']);
        } else {
            $this->validate($request, ['role' => 'required|exists:bouncer_roles,id']);
            $user->retract($user->roles()->get());
            $user->assign(Role::find($request->role));
            session()->flash('status', __('Proccess OK'));

            return redirect()->route('user.index');
        }
    }
}

resources/views/admin/users/admins.blade.php
@extends('layouts.app')
@section('titleOption',__('options.admin'))
@section('bar-search')
    @include('partials.search',[
      'route'=>route('admin.index'),
      'placeholder'=>__('labels.search',['name'=>__('labels.name')]),
      'filter'=>$filter
    ])
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
<div class="col-md-12">
            <div class="card">
             

                    <div class="card-header header-elements-inline">
                        <h5 class="card-title">@lang('options.table',['name'=>__('options.admin')])</h5>
                        <div class="header-elements">
                            <div class="list-icons">
                                    @can ('create-admin')
                                        <a href="{{route('admin.create')}}" class="btn badge-info badge-rounded waves-effect waves-light btn-sm text-white">
                                            @lang('labels.add')</a>
                                    @endcan
                            </div>
                        </div>
                    </div>



                    <div class="card-body collapse show">
                        <div class="table-responsive">
                            <table id="tableAccordion" class="table product-overview table-responsive-stack">
                                <thead>
                                    <tr>
                                            <th class="text-center">@lang('labels.image')</th>
                                            <th class="text-center">@lang('labels.name')</th>    
                                            <th  class="text-center"> @lang('labels.email') </th>
                                            <th  class="text-center"> @lang('labels.status') </th>
                                            <th class="text-center"> @lang('labels.actions')  </th>
                                    </tr>
                                </thead>
                                <tbody>
                                        @forelse($admins as $admin)
                                   
                                    <tr>
                                        <td>
                                            <img onerror="this.onerror=null;this.src='{{asset('images/user.png')}}';" src="{{$admin->avatar}}" alt="admin" width="50">
                                        </td>
                                        <td>{{$admin->name}}</td> 
                                        <td class="text-center">{{$admin->email}}</td>
                                        <td class="text-center">
                                            @if($admin->status=='A')
                                                <span class="label label-success font-weight-100">@lang('labels.active') </span>
                                            @else
                                                <span class="label label-danger font-weight-100">@lang('labels.inactive') </span>
                                            @endif
                                        </td>
                                        <td class="text-center">
                                        <form  action="{{route('admin.destroy',$admin->id)}}" id="frmDelete{{$admin->id}}" method="POST" class="form-horizontal" @submit.prevent="actionAlert($event)">
                                                @method('DELETE')
                                                @csrf
                                            @can('show-admin')     
                                            <a href="{{route('admin.show',$admin->id)}}" class="btn badge  waves-effect waves-light badge-success" 
                                                data-popup="tooltip"  title="" data-original-title="@lang('labels.view')">
                                                <i class="fas fa-user"></i></a>
                                            @endcan
                                            @can('role-admin')    
                                            <a href="{{route('change-role-admin',$admin->id)}}" class="btn badge  waves-effect waves-light badge-primary" 
                                                data-popup="tooltip"  title="" data-original-title="@lang('labels.change-role')">
                                                <i class="fas fa-sitemap"></i></a>
                                            @endcan
                                            @can('password-admin')
                                            <a href="{{route('change-password-admin',$admin->id)}}" class="btn badge  waves-effect waves-light badge-success" 
                                                data-popup="tooltip"  title="" data-original-title="@lang('labels.change-password')">
                                                <i class="fas fa-key"></i></a>
                                            @endcan  
                                            @can('update-admin')
                                            <a href="{{route('admin.edit',$admin->id)}}" class="btn badge  waves-effect waves-light badge-primary" 
                                            data-popup="tooltip"  title="" data-original-title="@lang('labels.edit')"><i class="fas fa-edit"></i></a> 
                                            @endcan  
                                            @can ('delete-admin')
                                                <button type="submit"  title="" data-popup="tooltip" 
                                                    data-original-title="@lang('labels.active-inactive-user')" class="btn waves-effect waves-light badge badge-danger">
                                                        <span><i class="fas fa-exchange-alt"></i></span>
                                                </button> 
                                            
                                            @endcan

                                        </form>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr><td colspan="5">@lang('labels.notresults')</td></tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
           


    </div></div>
</div>
@endsection

resources/views/admin/users/change-picture.blade.php
@extends('layouts.app')
@section('titleOption',__("options.change-picture"))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-4">
                    <div class="card">
                            <img class="card-img-top" src="{{asset('images/user_bg3.jpg')}}" alt="Card image cap" style="height: 140px">
                            <div class="card-body little-profile text-center">
                                <div class="pro-img"><img onerror="this.onerror=null;this.src='{{asset('images/user.png')}}';" src="{{$user->avatar}}" alt="user"></div>
                                <h3 class="m-b-0">{{$user->name}}</h3>
                              
                                {!! Form::open(['route'=>["changePicture"],'files'=>true]) !!}
                                <div class="text-left">
                                {!! Field::file('documentoFoto',['label'=>__('labels.image')])!!}
                            </div>
                                <div class="row text-center m-t-20">
                                    <div class="col-lg-6 col-md-6 m-t-20">
                                            <button type="submit" class="btn btn-info waves-effect waves-light  btn-block"> 
                                                <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                    </div>  
                                    <div class="col-lg-6 col-md-6 m-t-20">
                                        <a href='{{route("home")}}'  class="btn btn-danger waves-effect waves-light text-white  btn-block">
                                            <i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>

                                </div>
                                {!! Form::close() !!}
                            </div>
                    </div>       
             </div>     
    </div>
</div>
@endsection

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('titleOption',__("options.$type"))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-4">
                    <div class="card">
                            <img class="card-img-top" style="height: 110px" src="{{asset('images/userinfo.jpg')}}" alt="Card image cap">
                            <div class="card-body little-profile text-center">
                                <div class="pro-img"><img src="{{asset('images/user.png')}}" alt="user"></div>
                               
                                {!! Form::open(['route'=>["$type.store"]]) !!}
                                <div class="text-left">
                                
                                        {!! Field::text('name',null,['label'=>__('labels.name'),
                                        'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                
                                        {!! Field::email('email',null,['label'=>__('labels.email'),
                                        'placeholder'=>__('labels.input',['name'=>__('labels.email')])])!!}
                                
                                        {!! Field::password('password',['label'=>__('labels.password'),
                                        'placeholder'=>__('labels.select',['name'=>__('labels.password')])])!!}
                                
                                        {!! Field::select('role',$roles,null,['label'=>__('labels.role'),
                                        'empty'=>__('labels.select',['name'=>__('labels.role')])])!!}
                                           
                                </div>
                                <div class="row text-center m-t-20">
                                    <div class="col-lg-6 m-t-20">
                                            <button type="submit" class="btn btn-info waves-effect waves-light  btn-block"> 
                                                <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                    </div>  
                                    <div class="col-lg-6 m-t-20">
                                        <a href='{{route("$type.index")}}'  class="btn btn-danger waves-effect waves-light text-white btn-block">
                                            <i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>

                                </div>
                                {!! Form::close() !!}
                            </div>
                    </div>       
             </div>     
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('titleOption',__("options.$type"))
@section('content')
<div class="container">
    <div class="row justify-content-center">
            <div class="col-md-4">
                    <div class="card">
                            <img class="card-img-top" style="height: 110px" src="{{asset('images/userinfo.jpg')}}" alt="Card image cap">
                            <div class="card-body little-profile text-center">
                                <div class="pro-img"><img src="{{asset('images/user.png')}}" alt="user"></div>
                               
                                {!! Form::open(['route'=>["$type.update",$user->id],'method'=>'PUT']) !!}
                                <div class="text-left">
                                
                                        {!! Field::text('name',$user->name,['label'=>__('labels.name'),
                                        'placeholder'=>__('labels.input',['name'=>__('labels.name')])])!!}
                                
                                        {!! Field::email('email',$user->email,['label'=>__('labels.email'),
                                        'placeholder'=>__('labels.input',['name'=>__('labels.email')])])!!}
                                
                                       
                                
                                        {!! Field::select('role',$roles,optional($user->roles()->first())->id,['label'=>__('labels.role'),
                                        'empty'=>__('labels.select',['name'=>__('labels.role')])])!!}
                                           
                                </div>
                                <div class="row text-center m-t-20">
                                    <div class="col-lg-6 m-t-20">
                                            <button type="submit" class="btn btn-info waves-effect waves-light  btn-block"> 
                                                <i class="fa fa-check"></i> @lang('buttons.save')</button>
                                    </div>  
                                    <div class="col-lg-6 m-t-20">
                                        <a href='{{route("$type.index")}}'  class="btn btn-danger waves-effect waves-light text-white btn-block">
                                            <i class="fa fa-ban"></i> @lang('buttons.cancel')</a>
                                    </div>

                                </div>
                                {!! Form::close() !!}
                            </div>
                    </div>       
             </div>     
    </div>
</div>
@endsection

resources/views/admin/users/users.blade.php
@extends('layouts.app')
@section('titleOption',__('options.user'))
@section('bar-search')
    @include('partials.search',[
      'route'=>route('user.index'),
      'placeholder'=>__('labels.search',['name'=>__('labels.name')]),
      'filter'=>$filter
    ])
@endsection
@section('content')
<div class="container">
    <div class="row justify-content-center">
<div class="col-md-12">
            <div class="card">
                   

                    <div class="card-header header-elements-inline">
                        <h5 class="card-title">@lang('options.table',['name'=>__('options.user')])</h5>
                        <div class="header-elements">
                            <div class="list-icons">
                                    @can ('create-user')
                                        <a href="{{route('user.create')}}" class="btn badge-info badge-rounded waves-effect waves-light btn-sm text-white">
                                            @lang('labels.add')</a>
                                    @endcan
                            </div>
                        </div>
                    </div>



                    <div class="card-body collapse show">
                        <div class="table-responsive">
                            <table id="tableAccordion" class="table product-overview table-responsive-stack">
                                <thead>
                                    <tr>
                                            <th class="text-center">@lang('labels.image')</th>
                                            <th class="text-center">@lang('labels.name')</th>    
                                            <th  class="text-center"> @lang('labels.email') </th>
                                            <th  class="text-center"> @lang('labels.status') </th>
                                            <th class="text-center"> @lang('labels.actions')  </th>
                                    </tr>
                                </thead>
                                <tbody>
                                        @forelse($users as $user)
                                   
                                    <tr>
                                        <td>
                                            <img onerror="this.onerror=null;this.src='{{asset('images/user.png')}}';" src="{{$user->avatar}}" alt="user" width="50">
                                        </td>
                                        <td>{{$user->name}}</td> 
                                        <td class="text-center">{{$user->email}}</td>
                                        <td class="text-center">
                                            @if($user->status=='A')
                                                <span class="label label-success font-weight-100">@lang('labels.active') </span>
                                            @else
                                                <span class="label label-danger font-weight-100">@lang('labels.inactive') </span>
                                            @endif
                                        </td>
                                        <td class="text-center">
                                        <form  action="{{route('user.destroy',$user->id)}}" id="frmDelete{{$user->id}}" method="POST" class="form-horizontal" @submit.prevent="actionAlert($event)">
                                                @method('DELETE')
                                                @csrf
                                               
                                                @can('show-user')     
                                                <a href="{{route('user.show',$user->id)}}" class="btn badge  waves-effect waves-light badge-success" 
                                                    data-popup="tooltip"  title="" data-original-title="@lang('labels.view')">
                                                    <i class="fas fa-user"></i></a>
                                                @endcan

                                            @can('role-user')    
                                            <a href="{{route('change-role-user',$user->id)}}" class="btn badge  waves-effect waves-light badge-primary" 
                                                data-popup="tooltip"  title="" data-original-title="@lang('labels.change-role')">
                                                <i class="fas fa-sitemap"></i></a>
                                            @endcan
                                            @can('password-user')
                                            <a href="{{route('change-password-user',$user->id)}}" class="btn badge  waves-effect waves-light badge-success" 
                                                data-popup="tooltip"  title="" data-original-title="@lang('labels.change-password')">
                                                <i class="fas fa-key"></i></a>
                                            @endcan  
                                            @can('update-user')
                                            <a href="{{route('user.edit',$user->id)}}" class="btn badge  waves-effect waves-light badge-primary" 
                                            data-popup="tooltip"  title="" data-original-title="@lang('labels.edit')"><i class="fas fa-edit"></i></a> 
                                            @endcan  
                                            @can ('delete-user')
                                                <button type="submit"  title="" data-popup="tooltip" 
                                                    data-original-title="@lang('labels.active-inactive-user')" class="btn waves-effect waves-light badge badge-danger">
                                                        <span><i class="fas fa-exchange-alt"></i></span>
                                                </button> 
                                            
                                            @endcan

                                        </form>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr><td colspan="5">@lang('labels.notresults')</td></tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
           


    </div></div>
</div>
@endsection